name: Build and Save Production Files

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Install and build your site
      uses: withastro/action@v2
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: dist/
        retention-days: 14 